# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
    Congrats on merging your first pull request on the repository for ZoombieMania project 🎉! Keep Contributing.
# It is recommend to include as many gifs and emojis as possible